version: 2
jobs:
  deploy:
    working_directory: ~/workspace
    docker:
      - image: cibuilds/hugo:0.56
    environment:
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: deploy
          command: make deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: draft
