version: 2
jobs:
  deploy:
    branches:
      only:
        - draft
    working_directory: ~/workspace
    docker:
      - image: cibuilds/hugo:0.56
    environment:
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: deploy
          command: make deploy

